version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  buildAndTest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test
      - run: wget -qO - https://coverage.codacy.com/get.sh | sh -s -- report -r coverage/lcov.info

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildAndTest
