version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  buildAndTest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test
      - run: LATEST_VERSION="$(curl -Ls https://artifacts.codacy.com/bin/codacy-coverage-reporter/latest)"
      - run: echo $LATEST_VERSION
      - run: curl -Ls -o codacy-coverage-reporter "https://artifacts.codacy.com/bin/codacy-coverage-reporter/${LATEST_VERSION}/codacy-coverage-reporter-linux"
      - run: chmod +x codacy-coverage-reporter
      - run: codacy-coverage-reporter ./coverage/lcov.info

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildAndTest
