version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  buildAndTest:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: |
          npm run build
          npm test
          LATEST_VERSION="$(curl -Ls https://artifacts.codacy.com/bin/codacy-coverage-reporter/latest)"
          curl -Ls -o codacy-coverage-reporter "https://artifacts.codacy.com/bin/codacy-coverage-reporter/${LATEST_VERSION}/codacy-coverage-reporter-linux"
          chmod +x codacy-coverage-reporter
          ./codacy-coverage-reporter ./coverage/lcov.info

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildAndTest
