version: 2.1
orbs:
  node: circleci/node@5.1.0
  coverage-reporter: codacy/coverage-reporter@13.15.1
jobs:
  buildAndTest:
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test
  codacy-coverage-report:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: npm test
      - coverage-reporter/send_report:
          coverage-reports: report.xml,coverage.info
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - buildAndTest